ids/camera_id: 1
ids/fps: 15 # IDS-XS reaches at maximum 15 FPS
ids/width: 1280
ids/heigth: 720
ids/bpp: 24
ids/verbose: true
ids/rec_name: "" # let this field empty to disable the recording, please insert absolute address -- /home/solaris/catkin_ws/src/ids_viewer/rec/ids_viewer_rec.avi
ids/offline: true # when it is set the stream cames from ids/offline_name video, if it exists
ids/offline_name: "/home/solaris/catkin_ws/src/ids_viewer/rec/ids_viewer_rec_15fps.avi"